config/routes.rb
Rails.application.routes.draw do
  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post 'users/create' => 'users#create'
  get 'users/index'
  get 'users/:id' => 'users#show'
  get 'signup' => 'users#new'
  get 'posts/index'
  get 'posts/new' => 'posts#new'
  get 'posts/:id' => 'posts#show'
  post 'posts/create' => 'posts#create'
  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/update' => 'posts#update'
  post 'posts/:id/destroy' => 'posts#destroy'
  get '/' => "home#top"
  get 'about' => "home#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, {presence: true, length: {maximum: 140}}
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, {presence:true}
    validates :email, {presence:true, uniqueness:true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
  
  def show
    @post = Post.find_by(id: params[:id])
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(content: params[:content])
    if @post.save
      flash[:notice] = "Tweeted!"
      redirect_to("/posts/index")
    else
      render("posts/new")
    end
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    @post.content = params[:content]
    if @post.save
      flash[:notice] = "Editing was successful!"
      redirect_to("/posts/index")
    else
      # redirect_to("/posts/#{@post.id}/edit")
      render("posts/edit")
    end
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = "Deleted!"
    redirect_to("/posts/index")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(name: params[:name], email: params[:email])
    if @user.save
      flash[:notice] = "This user signup has completed!"
      redirect_to("/users/#{@user.id}")
    else
      render("/users/new")
    end
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    if @user.save
      flash[:notice] = "Edited"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="about-main">
  <h2>About Rails Sample Tweet App</h2>
  <p>
    Railsを用いたTwitter風サンプルアプリ<br>
    出典元：Progate Railsコース
  </p>
</div>

app/views/home/top.html.erb
<div class="main top-main">
  <div class="top-message">
    <h2>Rails Sample Tweet App</h2>
    <p>Tweet your posts</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Environment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-logo">
        <%= link_to "Rails Sample Tweet App", "/" %>
      </div>
      <ul class="header-menus">
        <li>
          <%= link_to "About Rails Sample Tweet App", about_path %>
        </li>
        <li>
          <%= link_to "Show posts", posts_index_path %>
        </li>
        <li>
          <%= link_to "Tweet a post", posts_new_path %>
        </li>
        <li>
          <%= link_to "Show users", users_index_path %>
        </li>
        <li>
          <%= link_to "Signup", signup_path %>
        </li>
        
      </ul>
    </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">Edit</h1>
    <%= form_tag("/posts/#{@post.id}/update") do %>
      <div class="form">
        <div class="form-body">
          <% @post.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
          <textarea name="content"><%= @post.content %></textarea>
          <input type="submit" value="save">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <% @posts.each do |post| %>
        <div class="posts-index-item">
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">Tweet a post</h1>
    <%= form_tag("/posts/create") do %>
      <div class="form">
        <div class="form-body">
          <% @post.errors.full_messages.each do |message| %>
            <div>
              <%= message %>
            </div>
          <% end %>
          <textarea name="content"><%= @post.content %></textarea>
          <input type="submit" value="tweet">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <%= @post.content %>
      <div class="post-time">
          <%= @post.created_at %>
      </div>
      <div class="post-menus">
        <%= link_to("Edit", "/posts/#{@post.id}/edit") %>
        <%= link_to("Delete", "/posts/#{@post.id}/destroy", {method: "post"}) %>
      </div>
      
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">Edit user infomation</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <%= form_tag("/users/#{@user.id}/update") do %>
            <p>User Name</p>
            <input class="inputstyle" name="name" value="<%= @user.name %>">
            <p>Email</p>
            <input class="inputstyle" name="email" value="<%= @user.email %>">
            <input type="submit" value="save">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">Show users</h1>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-right">
          <%= link_to(user.name, "/users/#{user.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">Signup</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <%= form_tag("/users/create") do %>
          <p>User Name</p>
          <input class="inputstyle" name="name" value="<%= @user.name %>">
          <p>Email</p>
          <input class="inputstyle" name="email" value="<%= @user.email %>">
          <input type="submit" value="Signup">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <li>
          <%= link_to( "Edit", "/users/#{@user.id}/edit") %>
      </li>
    </div>
  </div>
</div>